### ISSUE TITLE
TrinoConnection missing (rob)

### ISSUE THREAD

**Issue by fhennig** [stackabletech/superset-operator#153] opened 2022-03-14 16:33 UTC
From the CRD Review.

**Comment by sbernauer** [comment] 2022-05-11 08:39
I think this is a duplicate of https://github.com/stackabletech/superset-operator/issues/3

**Comment by maltesander** [comment] 2022-07-12 09:12
> I think this is a duplicate of #3

Yeah closing this!

**Closed by maltesander** 2022-07-12 09:12 UTC
Labels: status/needs-refinement

**Comment by Spikebady** [comment] 2022-09-22 02:45
It use to be clear.It is explicit video of my wife claiming to be a sleep.We are going through a court battle and I really need help proven that it exists
